# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11
language: swift

cache: 
- cocoapods
- xcpretty
podfile: Example/Podfile
rvm:
- 2.4.3
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- gem install xcpretty
- pod install --project-directory=Example

script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace AVSQLDebugger.xcworkspace -scheme AVSQLDebugger-Example -sdk iphonesimulator13.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
